spring:
  cloud:
    gateway:
      routes:
        - id: USERPROFILE-SERVICE
          uri: lb://USERPROFILE-SERVICE
          predicates:
            - Path=/api/v1.0/userProfile/**
        - id: WISHLIST-SERVICE
          uri: lb://WISHLIST-SERVICE
          predicates:
            - Path=/api/**
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/**
        - id: MUSIC-SERVICE
          uri: lb://MUSIC-SERVICE
          predicates:
            - Path=/api/v1/music/**
