export const API_URL = "https://my-project-spotify-jd-env-1.eba-uiycbk6r.us-east-1.elasticbeanstalk.com/api/v1.0/"
export const API_URL_AUTH = API_URL+"auth"
export const API_URL_MUSIC = API_URL+"music"
export const API_URL_WISHLIST = API_URL+"wishlist"
export const API_URL_USERPROFILE = API_URL+"userProfile"